Updated UI/UX for auth pages
abe-mused/AccountabilityAppFrontEnd pull request #100
Opened 2022-11-24 07:44 UTC by mohammedali101

- Added CircularProgressIndicator (loading spinner) on all auth pages
- Fixed spelling and removed unnecessary comments
-  First video showcases sign in, reset password
- Second video displays sign up
- Image shares failed login

https://user-images.githubusercontent.com/91173297/203722646-1ac6209c-147e-41c3-9ead-ea262277d00b.mov

https://user-images.githubusercontent.com/91173297/203722622-8f7b196a-0bf7-4bbf-af39-59f673841885.mov

<img width="1440" alt="login failure " src="https://user-images.githubusercontent.com/91173297/203722824-c9756ba9-34cf-45c0-8f03-9535bedfd3a4.png">

2022-11-24 07:56 UTC, abe-mused commented
So when there's an error, it keeps spinning?

2022-11-24 07:59 UTC, abe-mused requested changes

2022-11-24 07:59 UTC, abe-mused commented on lib/auth_pages/sign_in.dart
> +                              const SignUpPage(),
keep on same line

2022-11-24 07:59 UTC, abe-mused commented on lib/auth_pages/sign_in.dart
> +                              doLogIn();
take `doLogIn()` out of `setState`

2022-11-24 07:59 UTC, abe-mused commented on lib/auth_pages/sign_up.dart
> +    }
Why do we need this? (we already have the `CircularProgressIndicator` below)

2022-11-24 22:14 UTC, mohammedali101 commented
> So when there's an error, it keeps spinning?

UPDATED:
 Future.delayed(const Duration(seconds: 1), (){
                              setState(() {
                                _updateResetPassword = false;
                              });

2022-11-25 07:00 UTC, abe-mused approved these changes
lgtm!

2022-11-25 07:01 UTC, merged