Delete comment
abe-mused/AccountabilityAppFrontEnd pull request #90
Opened 2022-11-13 20:22 UTC by mohammedali101

delete comment functionality added
total number of characters for comments added
making delete comment be reactive

2022-11-13 20:44 UTC, mohammedali101 commented
https://user-images.githubusercontent.com/91173297/201543655-ffd3e564-89be-463e-bd25-2ef9ac13b997.mov

Not included in video, but user is not allowed to exceed 256 characters in the comment body because of inputFormatters

image below shows user can only delete their comment
<img width="360" alt="user can only delete their comment" src="https://user-images.githubusercontent.com/91173297/201543735-256b3e69-a250-4bc0-9e66-5481dee64f86.png">

2022-11-14 00:52 UTC, mohammedali101 commented
https://user-images.githubusercontent.com/91173297/201554305-a73b6ad5-963a-4b2b-bbea-39bc2ca8203e.mov

2022-11-14 01:11 UTC, tanvirahmed725 requested changes

2022-11-14 01:11 UTC, tanvirahmed725 commented on lib/util/apis.dart
> +        print("Success!");
Lets get rid of unnecessary print statements.

2022-11-14 01:11 UTC, tanvirahmed725 commented on lib/pages/post_widgets/post_widget.dart
> +        print("Post has successfully been deleted!");
Let's get rid of unnecessary print statements.

2022-11-14 01:11 UTC, tanvirahmed725 commented on lib/pages/post_page/post_page.dart
> +        print("Comment has successfully been deleted!");
Unnecessary print statement.

2022-11-14 01:11 UTC, tanvirahmed725 commented on lib/pages/post_widgets/post_widget.dart
> +  }
lets get rid of this function

2022-11-14 02:12 UTC, merged